from app.services.auth_service import AuthService
from app.services.dashboard_service import DashboardService
from app.services.driver_service import DriverService
from app.services.expense_service import ExpenseService
from app.services.fuel_log_service import FuelLogService
from app.services.maintenance_service import MaintenanceService
from app.services.report_service import ReportService
from app.services.role_service import RoleService
from app.services.trip_service import TripService
from app.services.user_service import UserService
from app.services.vehicle_service import VehicleService
