from app.crud.base import BaseRepository
from app.crud.driver import DriverRepository
from app.crud.expense import ExpenseRepository
from app.crud.fuel_log import FuelLogRepository
from app.crud.maintenance import MaintenanceRepository
from app.crud.role import RoleRepository
from app.crud.trip import TripRepository
from app.crud.user import UserRepository
from app.crud.vehicle import VehicleRepository
